server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jingximarket_db?useSSL=false
    username: root
    password: workhard2
    flyway.baselineOnMigrate: true
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    flyway.baselineOnMigrate: true
    hibernate:
      naming:
        implicitStrategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl